<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Kendra Vorenkamp" />


<title>The Niagara River Watershed</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/simplex.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-1.1/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-1.1/highlight.js"></script>
<link href="site_libs/font-awesome-4.5.0/css/font-awesome.min.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />

</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 41px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 46px;
  margin-top: -46px;
}

.section h2 {
  padding-top: 46px;
  margin-top: -46px;
}
.section h3 {
  padding-top: 46px;
  margin-top: -46px;
}
.section h4 {
  padding-top: 46px;
  margin-top: -46px;
}
.section h5 {
  padding-top: 46px;
  margin-top: -46px;
}
.section h6 {
  padding-top: 46px;
  margin-top: -46px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>


<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">R Data Science Final Project</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/adammwilson/RDataScience">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">The Niagara River Watershed</h1>
<h3 class="subtitle"><em>The relationship between precipitation and river discharge</em></h3>
<h4 class="author"><em>Kendra Vorenkamp</em></h4>

</div>


<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>The Niagara River watershed is not only the land draining to the river, but also includes the drainage area of the other Great Lakes “upstream”: Lake Erie, Lake Huron, and Lake Michigan/Lake Superior. In order to investigate a relationship between precipitation within the watershed and discharge through the Niagara River, several problems arise in quantifying the data. First, the Lake Erie watershed data is international, shared with Canada. As of now, there is not a common dataset for the Great Lakes, making collaboration for watershed management difficult. Second, there may be a significant lag in precipitation events and discharge reaction with a watershed system this large. Third, snow melt and ice cover of the lakes will affect flow throughout the lakes, and the ability to measure discharge.</p>
<p>The questions I will be pursuing through this project are</p>
<ol style="list-style-type: decimal">
<li><p>Has the flow rate of the Niagara River changed over time?</p></li>
<li><p>Is there a relationship between precipitation and discharge in the Niagara River?</p></li>
<li><p>If so, what level of detail is needed to ascertain this relationship?</p></li>
</ol>
<p>My hypotheses to these questions are that yes, the flow rate has changed with time as land and water use has changed the watershed, there is a relationship between discharge and precipitation, and that it will be sufficient to incorporate flow from the St. Clair River (from Lake Huron), the subwatersheds surrounding Lake Erie, and the Niagara watershed to see a relationship to the discharge measured at the downstream end of the river.</p>
</div>
<div id="materials-and-methods" class="section level1">
<h1>Materials and methods</h1>
<p>Load any required packages (Some packages may need to be installed):</p>
<pre class="r"><code>library(magrittr)
library(sp)
library(xts)
library(zoo)
library(hydroTSM)
library(ggplot2)
library(dplyr)
library(tidyr)
library(readxl)
library(dataRetrieval)
library(data.table)
knitr::opts_chunk$set(cache=TRUE)  # cache the results for quick compiling</code></pre>
<p>My discharge data for the Niagara River comes from <a href="http://www.lre.usace.army.mil/Portals/69/docs/GreatLakesInfo/docs/DischargeMeasurement/DischargeData/NiagaraRiverDischargeData.csv">the Army Corps of Engineers website</a> The description of their Niagara River sampling locations are shown in the table below:</p>
<table>
<colgroup>
<col width="16%" />
<col width="7%" />
<col width="55%" />
<col width="20%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Location</th>
<th align="left">Established</th>
<th align="left">Description</th>
<th align="left">Measurements</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Bridge</td>
<td align="left">1897</td>
<td align="left">Along the downstream edge of the International Railroad Bridge, which spans the Niagara River from Buffalo, New York to Fort Erie, Ontario</td>
<td align="left">Made directly from the bridge</td>
</tr>
<tr class="even">
<td align="left">Open</td>
<td align="left">1899</td>
<td align="left">About 1,800 feet downstream of the International Railroad Bridge, just below Unity Island</td>
<td align="left">Not given</td>
</tr>
<tr class="odd">
<td align="left">Bridgeburg</td>
<td align="left">1921</td>
<td align="left">along the upstream edge of the International Railroad Bridge, which spans the Niagara River from Buffalo, New York to Fort Erie, Ontario</td>
<td align="left">Made directly from the bridge</td>
</tr>
<tr class="even">
<td align="left">BlackRock</td>
<td align="left">1931</td>
<td align="left">It was nearly identical to the Open Section. It was located about 1,800 feet north of the International Railroad Bridge, just below Unity Island.</td>
<td align="left">Not given</td>
</tr>
<tr class="odd">
<td align="left">Wickwire</td>
<td align="left">1931</td>
<td align="left">It was nearly identical to the Split Section, although little information is available from any previous measurements. It was it was located about 2-3/4 miles north of Buffalo, New York and spanned the river between the U. S. mainland and Grand Island.</td>
<td align="left">Not given</td>
</tr>
<tr class="even">
<td align="left">Oakfield</td>
<td align="left">1931</td>
<td align="left">It was nearly identical to the Split Section also, although little information is available from any previous measurements. This section traversed the river from Grand Island west to the Canadian mainland.</td>
<td align="left">Not given</td>
</tr>
<tr class="odd">
<td align="left">Austin Street</td>
<td align="left">1952</td>
<td align="left">On the upper Niagara River, it extended approximately 1,840 feet from the Canadian shore at Fort Erie, Ontario to Buffalo, New York, on the U. S. mainland.</td>
<td align="left">Not given</td>
</tr>
<tr class="even">
<td align="left">Stella Niagara</td>
<td align="left">1957</td>
<td align="left">In the lower Niagara River, about 1-1/2 miles below Lewiston, New York and extended from the Canadian to the U. S. mainland.</td>
<td align="left">Not given</td>
</tr>
<tr class="odd">
<td align="left">Maid-of -the -Mist</td>
<td align="left">1967</td>
<td align="left">It was located in the Maid-of the –Mist Pool, approximately 1,500 feet downstream of the Rainbow Bridge.</td>
<td align="left">Not given</td>
</tr>
<tr class="even">
<td align="left">Niagara</td>
<td align="left">1868</td>
<td align="left">In the lower Niagara River near Youngstown, New York, about 3 miles above the mouth of the river.</td>
<td align="left">Not given</td>
</tr>
<tr class="odd">
<td align="left">Chippewa Channel</td>
<td align="left">1967</td>
<td align="left">In the Chippewa Channel of the Niagara River about ½ mile below Bayer’s Creek. It extended between the Canadian mainland and Grand Island.</td>
<td align="left">Not given</td>
</tr>
<tr class="even">
<td align="left">Tonawanda Channel</td>
<td align="left">1967</td>
<td align="left">In the Tonawanda Channel of the Niagara River about 1/3 mile northeast of Two Mile Creek at Tonawanda, New York. It extended from the U. S. mainland to Grand Island.</td>
<td align="left">Not given</td>
</tr>
<tr class="odd">
<td align="left">International Railroad Bridge</td>
<td align="left">1970</td>
<td align="left">About 408 feet above the International Railroad Bridge on the upper Niagara River.</td>
<td align="left">Not given</td>
</tr>
<tr class="even">
<td align="left">American Falls</td>
<td align="left">1971</td>
<td align="left">consisted of two segments. The first was the Bridal Veil Channel segment, between Goat Island and Green Island. It was metered from the upstream side of the Bridal Veil portion of the Goat Island Bridge. The second was the American Falls Channel segment between Green Island and the U. S. mainland.</td>
<td align="left">Metered from the downstream side of the American Falls portion of the Bridge.</td>
</tr>
<tr class="odd">
<td align="left">Moses</td>
<td align="left">1971</td>
<td align="left">Located about 500 feet upstream of the Robert Moses Powerhouse tail race.</td>
<td align="left">Not given</td>
</tr>
<tr class="even">
<td align="left">Cableway</td>
<td align="left">1973</td>
<td align="left">A cableway was installed spanning the Niagara Gorge, approximately at the location of the Moses Section. It is about 500 feet upstream of the Robert Moses tail race on the lower Niagara River.</td>
<td align="left">Not given</td>
</tr>
</tbody>
</table>
</div>
<div id="coding-section" class="section level1">
<h1>Coding Section</h1>
<p>The comma separated value (csv) file that the above hyperlink returns can be downloaded straigt to R using the following code:</p>
<pre class="r"><code>Qdata&lt;-fread(&quot;http://www.lre.usace.army.mil/Portals/69/docs/GreatLakesInfo/docs/DischargeMeasurement/DischargeData/NiagaraRiverDischargeData.csv&quot;)
Qdata=select(Qdata,&#39;Cross.Section.Name&#39;=&#39;Cross-Section Name&#39;,&#39;Discharge&#39;=&#39;Discharge/tcfs&#39;, &#39;Year&#39;, &#39;Month&#39;,&#39;Day&#39;,&#39;Time&#39;=&#39;Start Time&#39;)
Qdata[Qdata$Year==1931&amp;Qdata$Month==9&amp;Qdata$Day==31,&quot;Day&quot;]=30</code></pre>
<pre><code>## Warning in `[&lt;-.data.table`(`*tmp*`, Qdata$Year == 1931 &amp; Qdata$Month == :
## Coerced &#39;double&#39; RHS to &#39;character&#39; to match the column&#39;s type; may have
## truncated precision. Either change the target column to &#39;double&#39; first
## (by creating a new &#39;double&#39; vector length 2004 (nrows of entire table) and
## assign that; i.e. &#39;replace&#39; column), or coerce RHS to &#39;character&#39; (e.g. 1L,
## NA_[real|integer]_, as.*, etc) to make your intent clear and for speed. Or,
## set the column type correctly up front when you create the table and stick
## to it, please.</code></pre>
<pre class="r"><code>head(Qdata)</code></pre>
<pre><code>##    Cross.Section.Name Discharge Year Month Day  Time
## 1:     American Falls      12.6 1971     6   2  8:00
## 2:     American Falls      13.4 1971     6   3  7:30
## 3:     American Falls      13.7 1971     6   3 10:05
## 4:     American Falls      13.4 1971     6   3 13:15
## 5:     American Falls      12.7 1971     6   3 14:55
## 6:     American Falls      10.3 1971     6   3 18:15</code></pre>
<p>Let’s work with the data now. I am going to compile the separate columns for the date: Year, Month, and Day; into a single Date column:</p>
<pre class="r"><code>Qdata$Date=as.Date( with(Qdata,paste(Year, Month , Day , sep = &quot;-&quot; ),&quot;12-31-9999&quot;, format = &quot;%Y-%m-%d&quot; ))
head(Qdata)</code></pre>
<pre><code>##    Cross.Section.Name Discharge Year Month Day  Time       Date
## 1:     American Falls      12.6 1971     6   2  8:00 1971-06-02
## 2:     American Falls      13.4 1971     6   3  7:30 1971-06-03
## 3:     American Falls      13.7 1971     6   3 10:05 1971-06-03
## 4:     American Falls      13.4 1971     6   3 13:15 1971-06-03
## 5:     American Falls      12.7 1971     6   3 14:55 1971-06-03
## 6:     American Falls      10.3 1971     6   3 18:15 1971-06-03</code></pre>
<p>We’ll find the monthly mean discharge and standard deviation for the Niagara River:</p>
<pre class="r"><code>meanQdata=Qdata%&gt;%
  group_by(Year,Month)%&gt;%
  summarise(meanDischarge = mean(Discharge,na.rm=T),
            sdDischarge = sd(Discharge,na.rm=T))
data.table(meanQdata)</code></pre>
<pre><code>##      Year Month meanDischarge sdDischarge
##   1: 1868     6     293.55455   25.905882
##   2: 1868     7     286.03000   19.715772
##   3: 1868     8     248.31000   12.142743
##   4: 1868     9     239.69286   27.894071
##   5: 1897    10     181.85000   12.328357
##  ---                                     
## 102: 1988     5     218.13289    6.353086
## 103: 1989     4      85.93333   25.768197
## 104: 1989     5     117.41714  106.290477
## 105: 1990     5      11.44000    1.406900
## 106: 1992     5     210.01695   47.195650</code></pre>
<p>I want to treat the data with the R package hydroTSM, which helps analyze hydrological data with time series. To do this, I need to get my data into a format that is compatible with the xts package.</p>
<pre class="r"><code>Qdata&lt;-data.table(Qdata)
QDT&lt;-as.data.table(Qdata)
head(QDT)</code></pre>
<pre><code>##    Cross.Section.Name Discharge Year Month Day  Time       Date
## 1:     American Falls      12.6 1971     6   2  8:00 1971-06-02
## 2:     American Falls      13.4 1971     6   3  7:30 1971-06-03
## 3:     American Falls      13.7 1971     6   3 10:05 1971-06-03
## 4:     American Falls      13.4 1971     6   3 13:15 1971-06-03
## 5:     American Falls      12.7 1971     6   3 14:55 1971-06-03
## 6:     American Falls      10.3 1971     6   3 18:15 1971-06-03</code></pre>
<pre class="r"><code>QDT&lt;-select(QDT,Date,Discharge)
Qxts&lt;-as.xts.data.table(QDT)</code></pre>
<p>The hydroTSM package contains a function to process daily data to monthly and annual. For my purposes, I want to see the monthly mean to make sure there is not too much discrepancy over the large time period in the measurements.</p>
<pre class="r"><code>meanMon&lt;-daily2monthly(Qxts,FUN=mean)
head(meanMon)</code></pre>
<pre><code>## 1868-06-01 1868-07-01 1868-08-01 1868-09-01 1897-10-01 1897-11-01 
##   293.5545   286.0300   248.3100   239.6929   181.8500   184.4000</code></pre>
<p>Now that we have it in a monthly time series format, let’s plot the data:</p>
<pre class="r"><code>mMon&lt;-plot(meanMon,
     type=&quot;p&quot;,
     ylab=&quot;Discharge (cfs)&quot;,
     xlab=&quot;Year&quot;,
     main=&quot;Monthly Mean Discharge of the Niagara River&quot;,
     col=&quot;blue&quot;
)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" width="672" /> hydroTSM has some required maintenance code for use in calculations:</p>
<pre class="r"><code>dates&lt;-time(meanMon)
nyears&lt;-yip(from = start(meanMon),to=end(meanMon),out.type = &quot;nmbr&quot;)</code></pre>
<p>Let’s take a look at the summary information for the Niagara River discharge measurements.</p>
<pre class="r"><code>smry(meanMon)</code></pre>
<pre><code>##               Index  meanMon
## Min.     1868-06-01   7.9750
## 1st Qu.  1908-08-16 120.3000
## Median   1957-11-16 188.7000
## Mean     1944-04-20 173.3000
## 3rd Qu.  1974-03-01 214.5000
## Max.     1992-05-01 293.6000
## IQR            &lt;NA&gt;  94.1745
## sd             &lt;NA&gt;  65.5914
## cv             &lt;NA&gt;   0.3785
## Skewness       &lt;NA&gt;  -0.8924
## Kurtosis       &lt;NA&gt;   0.1179
## NA&#39;s           &lt;NA&gt;   0.0000
## n              &lt;NA&gt; 106.0000</code></pre>
<p>From this, we can see that the lowest flow of record occurred in June 1868, with a flow of approximately 8 cfs and the highest flow occurred in May 1992 with approximately 294 cfs. The mean flow is 173 cfs.</p>
<p>HydroTSM can show the data in different ways to explore the hydrography of the region.</p>
<pre class="r"><code>hydroplot(meanMon,var.type = &quot;Flow&quot;,main = &quot;at Niagara River&quot;,pfreq = &quot;dm&quot;,from = &quot;1868-06-01&quot;)</code></pre>
<pre><code>## [Warning: &#39;x&#39; is a monthly object, so &#39;pfreq&#39; has been changed to &#39;ma&#39;]</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>It displays it as the time series, where it is observed that the flow of the Niagara River has seen a dramatic change since measurements began 124 years ago. 1967 was the first time when the monthly discharge averaged less than 100 cfs.</p>
<pre class="r"><code>M &lt;- matrix(m, ncol=53, byrow = TRUE)


require(lattice)</code></pre>
<pre><code>## Loading required package: lattice</code></pre>
<pre class="r"><code>print(matrixplot(M,ColorRamp = &quot;Days&quot;,main = &quot;Annual Flow at Niagara River (cfs)&quot;))</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-11-1.png" width="672" /> Plotting the monthly flow values for each year, useful for identifying high/low flow months.</p>
</div>

<!-- give the footer some space -->
<br/>
<br/>

<footer id="site-footer">
  <div id="footer1">
  This website is a project for Adam Wilson's <a href="http://www.adamwilson.us/RDataScience"><i> Spatial Data Science (GEO503) </i></a>Course at the University at Buffalo
  </div>
  <div id="footer2">
  <a rel="license" property="http://creativecommons.org/ns#license"
  href="http://creativecommons.org/licenses/by/4.0/" ><img src="img/cc-by.svg" alt="cc-by"/></a> 
  </div>
</footer>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>


</body>
</html>
